// Ethiopian regions and their zones
export const ethiopianRegions = [
  { region: 'Addis Ababa', zones: ['Not Applicable'] },
  { region: 'Affar', zones: ['Zone 1', 'Zone 2', 'Zone 3', 'Zone 4', 'Zone 5'] },
  { region: 'Amhara', zones: ['North Wollo', 'South Wollo', 'Oromia Zone', 'East Gojjam', 'West Gojjam', 'North Shewa'] },
  { region: 'Benishangul-Gumuz', zones: ['Assosa', 'Pawe', 'Bulen', 'Kamashi', 'Mao Komo'] },
  { region: 'Dire Dawa', zones: ['Not Applicable'] },
  { region: 'Gambella', zones: ['Itang', 'Lare', 'Majang', 'Nuer', 'Anuak'] },
  { region: 'Harari', zones: ['Not Applicable'] },
  { region: 'Oromia', zones: ['East Hararghe', 'West Hararghe', 'North Shewa', 'South Shewa', 'Bale', 'Guji', 'Borena', 'Arsi', 'West Wollega', 'East Wollega', 'Ilubabor', 'Jimma', 'Kellem Wollega'] },
  { region: 'SNNPR', zones: ['Sidamo', 'Gurage', 'Wolaita', 'Gamo Gofa', 'Kefa', 'South Omo', 'Bench Maji'] },
  { region: 'Somali', zones: ['Afmadu', 'Deghabur', 'Doolo', 'Fiq', 'Gode', 'Jijiga', 'Lij Momale', 'Shinile', 'Warder'] },
  { region: 'Tigray', zones: ['Central', 'Eastern', 'Northwestern', 'Southeastern', 'Southwestern', 'Western'] }
];

export const jobRoles = [
  'Domestic Worker',
  'Caregiver',
  'Cook',
  'House Cleaner',
  'Nanny',
  'Gardener',
  'Driver',
  'Security Guard',
  'Nurse',
  'Laboratory Technician',
  'Factory Worker',
  'Construction Worker',
  'Electrician',
  'Plumber',
  'Carpenter',
  'Welder',
  'Mechanic',
  'Chef',
  'Hotel Staff',
  'Restaurant Worker',
  'Sales Representative',
  'Customer Service',
  'Administrative Staff',
  'Data Entry',
  'Accountant',
  'Engineer',
  'Technician'
];

export const countries = [
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Jordan',
  'Lebanon',
  'Egypt',
  'Libya',
  'Djibouti',
  'South Sudan',
  'Kenya',
  'Uganda',
  'Tanzania',
  'Rwanda',
  'Burundi',
  'Democratic Republic of Congo',
  'South Africa',
  'Botswana',
  'Namibia',
  'Zimbabwe',
  'Mozambique',
  'Malawi',
  'Zambia',
  'Mauritius',
  'Seychelles',
  'Malaysia',
  'Singapore',
  'Indonesia',
  'Thailand',
  'Myanmar',
  'Philippines',
  'Vietnam',
  'Brunei',
  'Cambodia',
  'Laos',
  'Hong Kong',
  'Taiwan',
  'South Korea',
  'Japan',
  'Turkey',
  'Greece',
  'Italy',
  'Spain',
  'Portugal',
  'United Kingdom',
  'Ireland',
  'France',
  'Germany',
  'Netherlands',
  'Belgium',
  'Austria',
  'Switzerland',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Croatia',
  'Serbia',
  'Slovenia',
  'Slovakia',
  'Denmark',
  'Sweden',
  'Norway',
  'Finland',
  'Russia',
  'Ukraine',
  'Belarus',
  'Moldova',
  'Georgia',
  'Azerbaijan',
  'Armenia',
  'Israel',
  'Palestine',
  'Iraq',
  'Iran',
  'Afghanistan',
  'Pakistan',
  'India',
  'Nepal',
  'Bhutan',
  'Bangladesh',
  'Sri Lanka',
  'Maldives',
  'Thailand',
  'Canada',
  'United States',
  'Mexico',
  'Guatemala',
  'Belize',
  'Honduras',
  'El Salvador',
  'Nicaragua',
  'Costa Rica',
  'Panama',
  'Colombia',
  'Venezuela',
  'Guyana',
  'Suriname',
  'Brazil',
  'Peru',
  'Ecuador',
  'Bolivia',
  'Chile',
  'Argentina',
  'Uruguay',
  'Paraguay',
  'Australia',
  'New Zealand',
  'Fiji',
  'Samoa',
  'Vanuatu',
  'Kiribati',
  'Papua New Guinea',
  'Solomon Islands'
];

export const languages = [
  'Amharic',
  'Tigrinya',
  'Somali',
  'Afaan Oromo',
  'Gurage',
  'Sidaamu Afoo',
  'Wolayttatta',
  'English',
  'Arabic',
  'French',
  'Spanish',
  'Portuguese',
  'Italian',
  'German',
  'Dutch',
  'Turkish',
  'Farsi',
  'Pashto',
  'Urdu',
  'Hindi',
  'Bengali',
  'Tagalog',
  'Indonesian',
  'Thai',
  'Chinese Mandarin',
  'Cantonese',
  'Japanese',
  'Korean',
  'Russian',
  'Ukrainian',
  'Polish',
  'Greek'
];

export const genders = ['Male', 'Female', 'Other', 'Prefer not to say'];

export const maritalStatus = ['Single', 'Married', 'Divorced', 'Widowed', 'Separated'];

export const educationLevels = [
  'No formal education',
  'Primary school',
  'Secondary school',
  'High school',
  'Certificate/Diploma',
  'Bachelor\'s degree',
  'Master\'s degree',
  'Doctorate degree'
];

export const experienceLevels = [
  'No experience',
  '0-1 year',
  '1-3 years',
  '3-5 years',
  '5-10 years',
  '10+ years'
];

export const visaTypes = [
  'Work Visa',
  'Domestic Worker Visa',
  'Tourist Visa',
  'Business Visa',
  'Visit Visa',
  'Transit Visa',
  'Residence Permit'
];

export const documentTypes = [
  'National ID',
  'Passport',
  'Birth Certificate',
  'Medical Certificate',
  'Police Clearance',
  'Employment Contract',
  'Training Certificate',
  'Language Test Result',
  'Technical Skill Certificate',
  'Vaccination Card'
];

export const employmentStatus = [
  'Available',
  'In Process',
  'Deployed',
  'On Leave',
  'Resigned',
  'Terminated'
];
