'use client';

import { useState, useEffect } from 'react';
import { FileText, Download, Share2, Eye, Upload, Users, FileDown } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { jsPDF } from 'jspdf';

interface Employee {
  id: string;
  name: string;
  role?: string;
  destination?: string;
  status: string;
}

const CV_TEMPLATES = [
  { id: 'professional', name: 'Professional', description: 'Clean, corporate design' },
  { id: 'modern', name: 'Modern', description: 'Contemporary with accent colors' },
  { id: 'minimal', name: 'Minimal', description: 'Simple, text-focused layout' }
];

export function CvGenerator() {
  const router = useRouter();
  const [selectedEmployee, setSelectedEmployee] = useState<string>('');
  const [selectedTemplate, setSelectedTemplate] = useState('professional');
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedCv, setGeneratedCv] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/employees?limit=100')
      .then(res => res.json())
      .then(data => {
        if (data.data) setEmployees(data.data);
      })
      .catch(() => setEmployees([]));
  }, []);

  const handleGenerate = async () => {
    if (!selectedEmployee) return;
    setIsGenerating(true);
    
    try {
      const res = await fetch(`/api/employees/${selectedEmployee}`);
      const data = await res.json();
      
      if (data.success) {
        const html = generateCvHtml(data.data, selectedTemplate);
        setGeneratedCv(html);
      }
    } catch (error) {
      console.error('Error generating CV:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!generatedCv) return;
    
    const blob = new Blob([generatedCv], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cv-${selectedEmployee}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = async () => {
    if (!selectedEmployee) return;
    setIsGenerating(true);
    
    try {
      const res = await fetch(`/api/employees/${selectedEmployee}`);
      const data = await res.json();
      
      if (data.success) {
        generateAndDownloadPdf(data.data, selectedTemplate);
      }
    } catch (error) {
      console.error('Error generating PDF:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const generateAndDownloadPdf = (employee: any, template: string) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;
    
    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(employee.name, pageWidth / 2, y, { align: 'center' });
    y += 10;
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(employee.role || 'Employee', pageWidth / 2, y, { align: 'center' });
    y += 8;
    
    if (employee.destination) {
      doc.text(`Destination: ${employee.destination}`, pageWidth / 2, y, { align: 'center' });
      y += 10;
    }
    
    // Divider
    doc.setDrawColor(226, 232, 240);
    doc.line(20, y, pageWidth - 20, y);
    y += 10;
    
    // Info section
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Personal Information', 20, y);
    y += 8;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Employee ID: ${employee.id}`, 20, y);
    y += 6;
    doc.text(`Status: ${employee.status}`, 20, y);
    y += 6;
    doc.text(`Created: ${new Date(employee.createdAt).toLocaleDateString()}`, 20, y);
    y += 12;
    
    // Documents
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Documents', 20, y);
    y += 8;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const docCount = employee.documents?.length || 0;
    doc.text(`${docCount} document(s) on file`, 20, y);
    y += 12;
    
    // Travel
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Travel History', 20, y);
    y += 8;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const travelCount = employee.travels?.length || 0;
    doc.text(`${travelCount} trip(s) recorded`, 20, y);
    
    // Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by Ethio Agency Hub - ${new Date().toLocaleDateString()}`, pageWidth / 2, 280, { align: 'center' });
    
    doc.save(`cv-${employee.name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
  };

  return (
    <div className="space-y-6">
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <h3 className="text-lg font-bold">Generate CV</h3>
        <p className="mt-1 text-sm text-slate-500">Create professional CVs for employees from stored data.</p>
        
        <div className="mt-6 grid gap-6 md:grid-cols-2">
          <div>
            <label className="mb-2 block text-sm font-medium">Select Employee</label>
            <select
              value={selectedEmployee}
              onChange={(e) => setSelectedEmployee(e.target.value)}
              className="w-full rounded-xl border border-slate-200 px-4 py-2.5"
            >
              <option value="">Choose employee...</option>
              {employees.map(emp => (
                <option key={emp.id} value={emp.id}>
                  {emp.name} - {emp.role || 'No role'}
                </option>
              ))}
            </select>
          </div>
          
          <div>
            <label className="mb-2 block text-sm font-medium">Template</label>
            <select
              value={selectedTemplate}
              onChange={(e) => setSelectedTemplate(e.target.value)}
              className="w-full rounded-xl border border-slate-200 px-4 py-2.5"
            >
              {CV_TEMPLATES.map(t => (
                <option key={t.id} value={t.id}>{t.name}</option>
              ))}
            </select>
          </div>
        </div>

        <button
          onClick={handleGenerate}
          disabled={!selectedEmployee || isGenerating}
          className="mt-6 flex items-center gap-2 rounded-xl bg-brand-600 px-6 py-2.5 font-medium text-white disabled:opacity-50"
        >
          {isGenerating ? (
            <>Generating...</>
          ) : (
            <>
              <FileText className="h-4 w-4" />
              Generate CV
            </>
          )}
        </button>
        <button
          onClick={handleDownloadPdf}
          disabled={!selectedEmployee || isGenerating}
          className="mt-6 ml-4 flex items-center gap-2 rounded-xl bg-emerald-600 px-6 py-2.5 font-medium text-white disabled:opacity-50"
        >
          <FileDown className="h-4 w-4" />
          Download PDF
        </button>
      </section>

      {generatedCv && (
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-bold">Preview</h3>
            <div className="flex gap-2">
              <button
                onClick={handleDownloadPdf}
                className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-medium text-emerald-700 hover:bg-emerald-100"
              >
                <FileDown className="h-4 w-4" />
                PDF
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium hover:bg-slate-50"
              >
                <Download className="h-4 w-4" />
                HTML
              </button>
              <button
                onClick={() => {
                  const blob = new Blob([generatedCv], { type: 'text/html' });
                  const url = URL.createObjectURL(blob);
                  window.open(url, '_blank');
                }}
                className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium hover:bg-slate-50"
              >
                <Eye className="h-4 w-4" />
                Open
              </button>
            </div>
          </div>
          <div className="mt-4 h-96 overflow-auto rounded-xl border border-slate-200 bg-slate-50 p-4">
            <iframe
              srcDoc={generatedCv}
              className="h-full w-full rounded"
              title="CV Preview"
            />
          </div>
        </section>
      )}

      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <h3 className="text-lg font-bold">Templates</h3>
        <div className="mt-4 grid gap-4 md:grid-cols-3">
          {CV_TEMPLATES.map(t => (
            <button
              key={t.id}
              onClick={() => setSelectedTemplate(t.id)}
              className={`rounded-xl border p-4 text-left transition-all ${
                selectedTemplate === t.id
                  ? 'border-brand-600 bg-brand-50'
                  : 'border-slate-200 hover:border-slate-300'
              }`}
            >
              <div className="flex h-24 items-center justify-center rounded-lg bg-slate-100">
                <FileText className="h-8 w-8 text-slate-400" />
              </div>
              <h4 className="mt-3 font-semibold">{t.name}</h4>
              <p className="text-sm text-slate-500">{t.description}</p>
            </button>
          ))}
        </div>
      </section>
    </div>
  );
}

function generateCvHtml(employee: any, template: string): string {
  const styles = template === 'modern' 
    ? 'background: #f8fafc; font-family: system-ui; padding: 40px;'
    : template === 'minimal'
    ? 'background: #fff; font-family: Georgia, serif; padding: 50px;'
    : 'background: #fff; font-family: Arial, sans-serif; padding: 40px;';

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { ${styles} }
    .header { text-align: center; margin-bottom: 30px; }
    .name { font-size: 28px; font-weight: bold; color: ${template === 'modern' ? '#0ea5e9' : '#1e293b'}; }
    .role { font-size: 16px; color: #64748b; margin-top: 5px; }
    .section { margin-bottom: 25px; }
    .section-title { font-size: 14px; font-weight: bold; text-transform: uppercase; color: #475569; border-bottom: 2px solid ${template === 'modern' ? '#0ea5e9' : '#e2e8f0'}; padding-bottom: 5px; margin-bottom: 15px; }
    .item { margin-bottom: 10px; }
    .item-title { font-weight: bold; color: #1e293b; }
    .item-sub { color: #64748b; font-size: 14px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="name">${employee.name}</div>
    <div class="role">${employee.role || 'Employee'}</div>
    ${employee.destination ? `<div class="role">Destination: ${employee.destination}</div>` : ''}
  </div>
  <div class="section">
    <div class="section-title">Information</div>
    <div class="grid">
      <div class="item">
        <div class="item-title">Status</div>
        <div class="item-sub">${employee.status}</div>
      </div>
      <div class="item">
        <div class="item-title">Employee ID</div>
        <div class="item-sub">${employee.id}</div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="section-title">Documents</div>
    <p class="item-sub">${employee.documents?.length || 0} documents on file</p>
  </div>
  <div class="section">
    <div class="section-title">Travel History</div>
    <p class="item-sub">${employee.travels?.length || 0} trips recorded</p>
  </div>
</body>
</html>
  `.trim();
}